# Generated by Django 5.1.1 on 2025-01-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_alter_product_stock_promotion_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'permissions': [('can_access_resource', 'Can access restricted resource')],
            },
        ),
    ]
