# Generated by Django 5.1.1 on 2025-01-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0003_yourmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('vizualizeaza_oferta', 'Permisiunea de a vizualiza oferta')]},
        ),
    ]
