# Generated by Django 5.1.1 on 2025-01-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
    ]
